# Generated by Django 3.1.13 on 2021-07-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.SlugField(unique=True, verbose_name='#tag')),
            ],
            options={
                'verbose_name': '#tag',
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_hashtag.hashtag', verbose_name='#tag')),
            ],
            options={
                'verbose_name': '#tag',
            },
        ),
        migrations.AddConstraint(
            model_name='taggeditem',
            constraint=models.UniqueConstraint(fields=('hashtag_id', 'content_type_id', 'object_id'), name='unique_tag'),
        ),
    ]
