# Generated by Django 3.1.13 on 2021-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hashtag', '0003_hashtag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='hashtags',
            field=models.ManyToManyField(related_name='tagged_items', to='django_hashtag.Hashtag', verbose_name='#tags'),
        ),
    ]
