# Generated by Django 3.1.13 on 2021-08-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_hashtag', '0005_reformat_hashtag_as_plaintext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggeditem',
            options={},
        ),
    ]
