# Generated by Django 3.1.13 on 2021-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hashtag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taggeditem',
            name='unique_tag',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='hashtags',
            field=models.ManyToManyField(to='django_hashtag.Hashtag', verbose_name='#tags'),
        ),
        migrations.AddConstraint(
            model_name='taggeditem',
            constraint=models.UniqueConstraint(fields=('content_type_id', 'object_id'), name='unique_item'),
        ),
    ]
