# Generated by Django 3.1.13 on 2021-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hashtag', '0002_change_to_m2m_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='hashtags',
            field=models.ManyToManyField(related_name='items', to='django_hashtag.Hashtag', verbose_name='#tags'),
        ),
    ]
