name: django-hashtag CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_coverage:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install .
        pip freeze --exclude-editable > requirements.txt
    - name: Run Tests
      run: |
        pwd
        coverage run
        ls -al
    - name: Coverage
      run: |
        pwd
        ls -al
        coverage report --fail-under=90
